In [1]:
%matplotlib inline
from pylab import *
from classy import *

Version  1.0.7
Version:  0.0.39


In [2]:
data=load_excel('data/iris.xls',verbose=True)

iris.data 151 5
150 vectors of length 4
Feature names: 'petal length in cm', 'petal width in cm', 'sepal length in cm', 'sepal width in cm'
Target values given.
Target names: 'Iris-setosa', 'Iris-versicolor', 'Iris-virginica'
Mean:  [3.75866667 1.19866667 5.84333333 3.054     ]
Median:  [4.35 1.3  5.8  3.  ]
Stddev:  [1.75852918 0.76061262 0.82530129 0.43214658]


In [3]:
C=NaiveBayes()

In [4]:
timeit(reset=True)
C.fit(data.vectors,data.targets)
print("Training time: ",timeit())

Time Reset
Training time:  0.0020580291748046875 seconds 


In [5]:
C.predict(atleast_2d(array([1,2,3,4])))

array([1])

In [6]:
C.save('test_save_naivebayes.json')

In [7]:
C1=NaiveBayes()

In [8]:
C1.load('test_save_naivebayes.json')
C1.predict(atleast_2d(array([1,2,3,4])))

array([1])

In [9]:
C=kNearestNeighbor()
C.fit(data.vectors,data.targets)
C.predict(atleast_2d(array([1,2,3,4])))

array([0])

In [10]:
C.save('test_save_kNearestNeighbor.json')

In [11]:
C1=kNearestNeighbor()

In [12]:
S1=dir(C1)
S2=dir(C)

In [13]:
set(S2)-set(S1)

{'_fit_X',
 '_fit_method',
 '_tree',
 '_y',
 'classes_',
 'effective_metric_',
 'effective_metric_params_',
 'n_features_in_',
 'n_samples_fit_',
 'outputs_2d_'}

In [14]:
C1=kNearestNeighbor()
C1.load('test_save_kNearestNeighbor.json')
C1.predict(atleast_2d(array([1,2,3,4])))

array([0])

In [15]:
C=CSC()
C.fit(data.vectors,data.targets)
C.predict(atleast_2d(array([1,2,3,4])))

array([0])

In [16]:
C1=CSC()

In [17]:
S1=dir(C1)
S2=dir(C)
set(S2)-set(S1)

{'classes_'}

In [18]:
C.save('test_save_CSC.json')

In [19]:
C1.load('test_save_CSC.json')
C1.predict(atleast_2d(array([1,2,3,4])))

array([0])

In [20]:
C=RCE()
C.fit(data.vectors,data.targets)
C.predict(atleast_2d(array([1,2,3,4])))

array([0])

In [21]:
C.save('test_save_RCE.json')

In [22]:
C1=RCE()
C1.load('test_save_RCE.json')
C1.predict(atleast_2d(array([1,2,3,4])))

array([0])

In [23]:
C=NumPyNetBackProp({
    'input':4,               # number of features
    'output':(3,'linear'),  # number of classes
    'cost':'mse',
})

In [24]:
C.fit(data.vectors,data.targets,epochs=3000)

layer       filters  size              input                output
   0 input                   150 x   1 x   1 x   4   ->   150 x   1 x   1 x   4
   1 connected               150 x   1 x   1 x   4   ->   150 x   3
   2 cost                    150 x   1 x   1 x   3   ->   150 x   1 x   1 x   3


100%|█████████████████████████████████████████████████████████| 3000/3000 [00:01<00:00, 1564.71it/s]


In [25]:
C.predict(atleast_2d(array([1,2,3,4])))

array([0])

In [26]:
C.save('test_save_nn.json')

In [27]:
M=C.model

In [28]:
M.save_model?

Signature: M.save_model(model_filename)
Docstring: Dump the current network model as pickle
File:      ~/anaconda3/lib/python3.11/site-packages/NumPyNet/network.py
Type:      method

In [29]:
M.load_model?

Signature: M.load_model(model_filename)
Docstring: Load network model object as pickle
File:      ~/anaconda3/lib/python3.11/site-packages/NumPyNet/network.py
Type:      method

In [30]:
L=C.model.__dict__['_net'][1]

In [31]:
M.__dict__

{'batch': 1,
 'train': None,
 'w': 1,
 'h': 1,
 'c': 4,
 '_net': [<NumPyNet.layers.input_layer.Input_layer at 0x163099510>,
 'metrics': [<function classy.supervised_numpynet.accuracy(y_true, y_pred)>],
 '_fitted': True,
 'layer_index': 3}

In [32]:
C.model.batch

1

In [33]:
C1=NumPyNetBackProp({
    'input':4,               # number of features
    'output':(3,'linear'),  # number of classes
    'cost':'mse',
})

In [34]:
C1.init_model(C.model.batch)

layer_weights=[L.weights if 'weights' in L.__dict__ else [] for L in C.model._net ]
layer_bias=[L.bias if 'bias' in L.__dict__ else [] for L in C.model._net ]

for L,W,B in zip(C1.model._net,layer_weights,layer_bias):
    if 'weights' in L.__dict__:
        L.weights=W
        L.bias=B

C1.model._fitted=True

layer       filters  size              input                output
   0 input                     1 x   1 x   1 x   4   ->     1 x   1 x   1 x   4
   1 connected                 1 x   1 x   1 x   4   ->     1 x   3
   2 cost                      1 x   1 x   1 x   3   ->     1 x   1 x   1 x   3


In [35]:
C1.predict(atleast_2d(array([1,2,3,4])))

array([0])

In [36]:
C.predict(atleast_2d(array([1,2,3,4])))

array([0])

In [37]:
C1=NumPyNetBackProp()
C1.load('test_save_nn.json')
C1.predict(atleast_2d(array([1,2,3,4])))

layer       filters  size              input                output
   0 input                     1 x   1 x   1 x   4   ->     1 x   1 x   1 x   4
   1 connected                 1 x   1 x   1 x   4   ->     1 x   3
   2 cost                      1 x   1 x   1 x   3   ->     1 x   1 x   1 x   3


array([2])